version: "3"
services:
  db:
    container_name: db
    image: postgres

    environment:
      POSTGRES_PASSWORD: lucid
      POSTGRES_USER: lucid
      POSTGRES_DB: lucid
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
